@host=http://localhost:8080/api
# @host=https://lifelink1-gold.vercel.app/api

post {{host}}/users/register
Content-Type: application/json

{
    "username": "mayowa",
    "email": "mayowa@gmail.com",
    "password": "mayowa",
    "fullname": "mayowa"
}

####
post {{host}}/users/login
Content-Type: application/json

{
    "email": "mayowa@gmail.com",
    "password": "mayowa"
}
###
get {{host}}/users/all

###
post {{host}}/hospitals/register
Content-Type: application/json

{
    "name": "saubana hospital",
    "email":"yusufsaubana04@gmail.com",
    "password": "saubana",
    "type": "public",
    "address": "Nithub"
}
###
post {{host}}/hospitals/verify
Content-Type: application/json

{
    "email":"yusufsaubana04@gmail.com"
}
###
post {{host}}/hospitals/login
Content-Type: application/json

{
    "email":"yusufsaubana04@gmail.com",
    "password": "saubana"
}

###
get {{host}}/hospitals/get-user-profile/test

###
get {{host}}/users/profile

###
put {{host}}/hospitals/update-user-profile/test
Content-Type: application/json

{"gender": "Female", "address": "Nithub"}
###
get {{host}}/users/all

###
POST {{host}}/hospitals/create-doctor
Content-Type: application/json

{
  "fullName": "testdoc",
  "username": "testdoc",
  "email": "testdoc@gmail.com",
  "dateOfBirth": "1990-01-01T00:00:00.000Z",
  "gender": "Male",
  "speciality": "Cardiology",
  "phoneNumber": 1234567890,
  "bio": "Doctor Femi is a cardiologist"
}

###
get {{host}}/hospitals/get-doctors

###
post {{host}}/doctors/login
Content-Type: application/json

{"email": "testdoc@gmail.com", "password": "123456"}

###
post {{host}}/doctors/consultation
Content-Type: application/json

{"patient": "test", "conversation": " Hi doc I'm feeling really sick I've had a fever for the past two days yeah it's been really bad okay and I've also been having some trouble breathing what do you think it is well let's take a look I've been having some chest pain too okay I'll listen to your lungs and check your temperature"}

###

get {{host}}/doctors/get-consultations?username=test

###
post {{host}}/pack/create
Content-Type: application/json

{"name": "nithub"}

###
post {{host}}/pack/join
Content-Type: application/json

{"id": "F2DFWJ"}

###
post {{host}}/pack/leave
Content-Type: application/json

{"id": "7APIOR"}

####
get {{host}}/pack/members/22KPW8

###
post {{host}}/pack/summarize-history
Content-Type: application/json

{"username": "testlong", "medicalIssue": "headache"}

###
post {{host}}/doctors/create-patient
Content-Type: application/json

{
    "username": "bayo",
    "email": "bayo@gmail.com",
    "password": "bayo",
    "fullname": "bayo"
}